
install.packages("remotes")
remotes::install_github("ncsu-landscape-dynamics/rpops")
library(PoPS)

cbs_path = "/Volumes/rs1/researchers/c/cmjone25/Data/Raster/USA/pops_casestudies/citrus_black_spot/outputs"

PoPS::calibrate(
  infected_years_file = list.files(path = paste0(cbs_path, "infection/"), pattern = "\\.tiff"),
  number_of_observations = 1,
  prior_number_of_observations = 0,
  prior_means = c(0, 0, 0, 0, 0, 0),
  prior_cov_matrix = matrix(0, 6, 6),
  params_to_estimate = c(TRUE, TRUE, TRUE, TRUE, FALSE, FALSE),
  number_of_generations = 7,
  generation_size = 1000,
  pest_host_table = "",
  competency_table = "",
  infected_file_list = "",
  host_file_list = list.files(path = paste0(cbs_path, "host/"), pattern = "\\.tiff"),
  total_populations_file = "",
  temp = TRUE,
  temperature_coefficient_file = list.files(path = paste0(cbs_path, "temp/"), pattern = "\\.tiff"),
  precip = TRUE,
  precipitation_coefficient_file = list.files(path = paste0(cbs_path, "precip/"), pattern = "\\.tiff"),
  model_type = "SI",
  latency_period = 0,
  time_step = "day",
  season_month_start = 1,
  season_month_end = 12,
  start_date = "2010-01-01",
  end_date = "2022-12-31",
  use_survival_rates = FALSE,
  survival_rate_month = 3,
  survival_rate_day = 15,
  survival_rates_file = "",
  use_lethal_temperature = FALSE,
  temperature_file = "",
  lethal_temperature = -12.87,
  lethal_temperature_month = 1,
  mortality_frequency = "year",
  mortality_frequency_n = 1,
  management = FALSE,
  treatment_dates = c('2010_05_01','2010_06_01','2010_07_01','2010_08_10','2010_09_19'),
  treatments_file = "",
  treatment_method = "ratio",
  natural_kernel_type = "cauchy",
  anthropogenic_kernel_type = "cauchy",
  natural_dir = "NONE",
  natural_kappa = 0,
  anthropogenic_dir = "NONE",
  anthropogenic_kappa = 0,
  pesticide_duration = c(0),
  pesticide_efficacy = c(30,30,40,40,40),
  mask = NULL,
  output_frequency = "year",
  output_frequency_n = 1,
  movements_file = "",
  use_movements = FALSE,
  start_exposed = FALSE,
  generate_stochasticity = TRUE,
  establishment_stochasticity = TRUE,
  movement_stochasticity = TRUE,
  dispersal_stochasticity = TRUE,
  establishment_probability = 0.5,
  dispersal_percentage = 0.99,
  quarantine_areas_file = "",
  use_quarantine = FALSE,
  use_spreadrates = FALSE,
  use_overpopulation_movements = FALSE,
  overpopulation_percentage = 0,
  leaving_percentage = 0,
  leaving_scale_coefficient = 1,
  calibration_method = "ABC",
  number_of_iterations = 1e+05,
  exposed_file_list = "",
  verbose = TRUE,
  write_outputs = "summary_outputs",
  output_folder_path = cbs_path,
  network_filename = "",
  network_movement = "walk",
  success_metric = "mcc",
  use_initial_condition_uncertainty = FALSE,
  use_host_uncertainty = FALSE,
  weather_type = "deterministic",
  temperature_coefficient_sd_file = "",
  precipitation_coefficient_sd_file = "",
  dispersers_to_soils_percentage = 0,
  quarantine_directions = "",
  multiple_random_seeds = FALSE,
  file_random_seeds = NULL,
  use_soils = FALSE,
  soil_starting_pest_file = "",
  start_with_soil_populations = FALSE,
  county_level_infection_data = FALSE
)


pops_multirun(infected_file_list = list.files(path = paste0(path, "infection/"), pattern = "\\.tiff"),
              host_file_list = list.files(path = paste0(path, "host/"), pattern = "\\.tiff"),
              temp = TRUE,
              temperature_coefficient_file = list.files(path = paste0(path, "temp/"), pattern = "\\.tiff"),
              precip = TRUE,
              precipitation_coefficient_file = list.files(path = paste0(path, "precip/"), pattern = "\\.tiff"),
              time_step = 'day',
              season_month_start = 9,
              season_month_end = 4,
              start_date = '2010-03-10',
              end_date = '2010-12-31',
              treatment_dates = c('2010_05_01','2010_06_01','2010_07_01','2010_08_10','2010_09_19'),
              pesticide_duration = c(30,30,40,40,40),
              pesticide_efficacy = 0.897,
              output_folder_path = "/Volumes/rs1/researchers/c/cmjone25/Data/Raster/USA/pops_casestudies/citrus_black_spot/outputs")

path = "/Volumes/cmjone25/Data/Raster/USA/pops_casestudies/citrus_black_spot/"
